#Conexión a la Base de Datos

In [2]:
from sqlalchemy import create_engine, text
import pandas as pd

engine = create_engine(
    "postgresql+psycopg2://postgres:lol123@localhost:5432/spotify_analysis"
)

with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM spotify_tracks"))
    print(f" Conectado — {result.fetchone()[0]:,} filas")

 Conectado — 113,999 filas

Top géneros por popularidad

In [3]:
q1 = """
SELECT track_genre,
       ROUND(AVG(popularity)::numeric, 2) AS avg_popularity,
       COUNT(*) AS total_tracks
FROM spotify_tracks
GROUP BY track_genre
ORDER BY avg_popularity DESC
LIMIT 15;
"""
df_q1 = pd.read_sql(text(q1), engine)
df_q1

          track_genre  avg_popularity  total_tracks
0            pop-film           59.28          1000
1               k-pop           56.95           999
2               chill           53.65          1000
3                 sad           52.38          1000
4              grunge           49.59          1000
5              indian           49.54          1000
6               anime           48.77          1000
7                 emo           48.13          1000
8           sertanejo           47.87          1000
9                 pop           47.58          1000
10  progressive-house           46.62          1000
11              piano           45.27          1000
12           mandopop           45.03          1000
13         deep-house           44.81          1000
14             brazil           44.67          1000

Top 10 canciones más populares

In [4]:
q2 = """
SELECT track_name, artists, track_genre, popularity, cluster_name
FROM spotify_tracks
ORDER BY popularity DESC
LIMIT 10;
"""
df_q2 = pd.read_sql(text(q2), engine)
df_q2

,track_name,artists,track_genre,popularity,cluster_name
0,Unholy (feat. Kim Petras),Sam Smith;Kim Petras,dance,100,Hard Rock / Metal
1,Unholy (feat. Kim Petras),Sam Smith;Kim Petras,pop,100,Hard Rock / Metal
2,"Quevedo: Bzrp Music Sessions, Vol. 52",Bizarrap;Quevedo,hip-hop,99,Pop / Dance
3,La Bachata,Manuel Turizo,latino,98,Pop / Dance
4,La Bachata,Manuel Turizo,latin,98,Pop / Dance
5,I'm Good (Blue),David Guetta;Bebe Rexha,dance,98,Hard Rock / Metal
6,I'm Good (Blue),David Guetta;Bebe Rexha,edm,98,Hard Rock / Metal
7,La Bachata,Manuel Turizo,reggae,98,Pop / Dance
8,I'm Good (Blue),David Guetta;Bebe Rexha,pop,98,Hard Rock / Metal
9,La Bachata,Manuel Turizo,reggaeton,98,Pop / Dance

Perfil promedio por cluster

In [5]:
q3 = """
SELECT cluster_name,
       ROUND(AVG(danceability)::numeric, 3) AS avg_dance,
       ROUND(AVG(energy)::numeric, 3)       AS avg_energy,
       ROUND(AVG(valence)::numeric, 3)       AS avg_valence,
       ROUND(AVG(tempo)::numeric, 1)         AS avg_tempo,
       COUNT(*)                              AS total
FROM spotify_tracks
GROUP BY cluster_name
ORDER BY avg_energy DESC;
"""
df_q3 = pd.read_sql(text(q3), engine)
df_q3

,cluster_name,avg_dance,avg_energy,avg_valence,avg_tempo,total
0,Hard Rock / Metal,0.469,0.815,0.371,139.2,28462
1,Electronic Instrumental,0.582,0.746,0.338,126.9,12057
2,Pop / Dance,0.696,0.732,0.700,117.8,37514
3,Hip-Hop / Rap,0.652,0.656,0.510,118.2,4525
4,Acoustic / Folk,0.527,0.383,0.395,113.1,23925
5,Classical / Ambient,0.346,0.176,0.184,102.9,7516

Géneros con más canciones trending

In [6]:
q4 = """
SELECT track_genre,
       COUNT(*) AS trending_tracks,
       ROUND(AVG(popularity)::numeric, 1) AS avg_popularity
FROM spotify_tracks
WHERE popularity > 80
GROUP BY track_genre
ORDER BY trending_tracks DESC
LIMIT 10;
"""
df_q4 = pd.read_sql(text(q4), engine)
df_q4

  track_genre  trending_tracks  avg_popularity
0         pop              114            86.1
1       dance               89            84.2
2        rock               80            84.1
3      latino               71            85.4
4     hip-hop               58            84.7
5   reggaeton               58            85.8
6       indie               43            83.9
7      reggae               40            87.0
8       house               34            83.6
9         edm               29            84.2

Canciones explícitas vs no explícitas

In [7]:
q5 = """
SELECT 
    CASE WHEN explicit = 1 THEN 'Explícita' ELSE 'No explícita' END AS tipo,
    ROUND(AVG(popularity)::numeric, 2) AS avg_popularity,
    ROUND(AVG(danceability)::numeric, 3) AS avg_dance,
    ROUND(AVG(energy)::numeric, 3) AS avg_energy,
    COUNT(*) AS total
FROM spotify_tracks
GROUP BY explicit;
"""
df_q5 = pd.read_sql(text(q5), engine)
df_q5

           tipo  avg_popularity  avg_dance  avg_energy   total
0  No explícita           32.94      0.560       0.634  104252
1     Explícita           36.45      0.636       0.721    9747